#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Justus.QuestApp.View.Droid.Resource", IsApplication=true)]

namespace Justus.QuestApp.View.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int activeQuestListLayout = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int childItemLayout = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int groupItemTable = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int layoutForButtons = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int questAddChild = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int questChildrenButton = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int questDescription = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int questDone = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int questEdit = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int questFailed = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int questListHeader = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int questProgress = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int questStatus = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int questTimeLeft = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int questTitle = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int questsListAdd = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int questsListBack = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int questsListTitle = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int scrollForButtons = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int subquestsList = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActiveQuestsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int QuestChildItemLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QuestGroupItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuestListHeader = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ErrorTitle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ProgressDialogTitle = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int QuestListAdd = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int QuestListBack = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int QuestListTitle = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040002
			public const int MatchParent = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int WrapContent = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int WrapContent_Button = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int WrapContent_QuestListTitle = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
